---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: asr-data-volume
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /home/someuser/dane-mount # fill in a valid path on a Kubernetes node (the local host if using minikube)
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube # note: change this when running on a proper k8s cluster