---
apiVersion: v1 # -------------- HOOK UP EXTERNAL ELASTICSEARCH ------------------------------------
kind: Service
metadata:
  name: elasticsearch
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: 9200
---
apiVersion: v1
kind: Endpoints
metadata:
  name: elasticsearch
subsets:
  - addresses:
    - ip: 44.242.32.23 #your (external) ES host
    ports:
      - port: 9200
---
apiVersion: v1 # -------------- DEFINE A VOLUME FOR THE DANE FS (READING INPUT, WRITING OUTPUT) ---
kind: PersistentVolume
metadata:
  name: asr-data-volume
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /home/someuser/dane-mount # fill in a valid path on a Kubernetes node (the local host if using minikube)
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube # note: change this when running on a proper k8s cluster