---
apiVersion: v1 #stores the login credentials taken from the minikube .docker/config.json (login to minikube)
kind: Secret #scp -i $(minikube ssh-key) docker@$(minkube ip):.docker/config.json .docker/config.json
metadata:
  name: xomg-docker-registry # kubectl create secret generic xomg-docker-registry --from-file=.dockerconfigjson=.docker/config.json --type=kubernetes.io/dockerconfigjson
data: #kubectl create secret docker-registry xomg-docker-registry --docker-server=dockerhub.rdlabs.beeldengeluid.nl --docker-user-name=xxx --docker-password=yyy
  .dockerconfigjson: .docker/config.json | base64
type: kubernetes.io/dockerconfigjson