[_]
schema-version="0.2"

[io.buildpacks]
name="beng-lod-server"
builder="gcr.io/buildpacks/builder"

[[io.buildpacks.build.env]]
name="GOOGLE_PYTHON_VERSION"
value="3.11.x"

[[io.buildpacks.build.env]]
name="GOOGLE_ENTRYPOINT"
value="src/server.py"