DEBUG: false
RABBITMQ:
    HOST: 'localhost'
    PORT: 5672
    EXCHANGE: 'DANE-exchange'
    RESPONSE_QUEUE: 'DANE-response-queue'
    USER: 'guest'
    PASSWORD: 'guest'
ELASTICSEARCH:
    HOST: 'localhost'
    PORT: 9200
    #USER: 'elastic'
    #PASSWORD: 'changeme'
    SCHEME: 'http'
DOCKER:
    ASR_CONTAINER: 'dane-asr'
    RABBITMQ_CONTAINER: 'dane-rmq'
ASR_API:
    HOST: 'localhost'
    PORT: 3023
    OUTPUT_DIR: '../mount/asr-output'
    SIMULATE: false
    WAIT_FOR_COMPLETION: true
DOWNLOAD:
    USE_DANE_DOWNLOADER: false
    LOCAL_DIR: '../mount/input-files'

