name: Build image and push to ECR

on:
  workflow_call:

jobs:
  build-and-push-ecr:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::917951871879:role/GitHubActionsBgOrg
        aws-region: eu-west-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Compile metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: "${{ steps.login-ecr.outputs.registry }}/dane-asr-worker-with-kaldi"
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        file: kaldi_included.Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: false
